kitti_rec:
  ros__parameters:
    sequence: 2
    data_dir: '/home/ubuntu/datahouse/kitti_odometry/dataset'
    odom_dir: '/home/ubuntu/datahouse/kitti_odometry/dataset'
    bag_dir : '/home/ubuntu/datahouse/kitti_odometry/bags02'
    odom : True
  
