kitti_rec:
  ros__parameters:
    sequence: 2
    data_dir: '/home/klogdev/datahouse/kitti_odometry_gray/dataset'
    odom_dir: '/home/klogdev/datahouse/kitti_odometry_gray/dataset'
    bag_dir : '/home/klogdev/datahouse/kitti_odometry_gray/bags02'
    odom : True
  
